---
 - set_fact:
      hostname1: "{{ incident_hostname }}.gdn.ge.com"
      #hostname1: "EMTwcSIDjakar01.gdn.ge.com"
 - name: Source Ping check 
   shell: ping -c 2 {{ hostname1 }}
   register: ping_result1
   ignore_errors: true
 - debug: var=ping_result1
 - set_fact: 
     result: |
              [code] <h3> PING RESULTS: </h3> [/code]
              {{ ping_result1.stdout }}

 - action: update_notes incident='{{ incident_no }}' work_notes='{{ result }}'

 - name:  when ping fails
   block:
   - name: check if its eligible to close
     action: Check_24hours_timestamp created_timestamp='{{ created_time }}'
     register: hourscheck_output
   - debug: var=hourscheck_output

   - name: Decide next action based on uptime and hours checks
     block:
      - name: Set evaluation facts
        ansible.builtin.set_fact:
         hour_output: "{{ hourscheck_output.output | default('') | string }}"
         hour_greater: "{{ 'greater than 23' in (hourscheck_output.output | default('') | string) }}"
         hour_lesser: "{{ 'lesser than 23' in (hourscheck_output.output | default('') | string) }}"
        ignore_errors: yes
      - block: 
        - ansible.builtin.debug:
            msg: "reassign to engineer and send email."
        - action: ReassigntoRenewableEngineer incident='{{ incident_no }}'
          register: output
        - debug: var=output
        
        - name: send email notification
          action: mail incident='{{ incident_no }}' hostname='{{ incident_hostname }}' short_description='{{ update_description }}'
          register: mail_output

        - debug: var=mail_output
        - set_fact: 
            result: |
              [code] Unable to ping. Reassigning [/code]

        - action: update_notes incident='{{ incident_no }}' work_notes='{{ result }}'
        - meta: end_play

        when: hour_greater

   - set_fact: 
      result: |
              [code] <h3> Unable to reach device. Next update is after 1hr </h3> [/code]

   - action: update_notes incident='{{ incident_no }}' work_notes='{{ result }}'

   - set_fact:
      current_status: "{{ state }}"
   - debug: var=current_status
   
   - block:
      - debug:
         msg: "move ticket to on hold"
      - name: Epoch + 1 hour
        set_fact:
         now_plus_1h: "{{ (ansible_date_time.epoch | int) + 3600 }}"

      - name: IST datetime string
        set_fact:
         now_plus_1h_ist: >-
            {{ now_plus_1h | to_datetime('%s', timezone='Asia/Kolkata')
                    | strftime('%Y-%m-%d %H:%M:%S') }}
      - action: Change_incident_state incident='{{ incident_no }}' follow_up='{{ now_plus_1h_ist }}'
        register: output
      - debug: var=output
     when: current_status == 'In Progress' or current_status == 'New'

   

   - meta: end_play
   when: "'64 bytes' not in ping_result1.stdout"

 - name:  when ping success
   block:
   - set_fact: 
      result: |
              [code] <h3> Device is reachable proceeding with further checks </h3> [/code]

   - action: update_notes incident='{{ incident_no }}' work_notes='{{ result }}'
   when: "'64 bytes' in ping_result1.stdout"
  
 #check for ticket status and move to pending



 

    

 