- name: test
  hosts: localhost
  tasks:
    - set_fact:
        #query: "short_descriptionLIKEDevice silencing^state=-1^end_dateBETWEENjavascript:gs.dateGenerate('2025-11-04','00:00:00')@javascript:gs.endOfToday()/change_request" 
        query: "short_descriptionLIKEDevice silencing^state=-1^end_dateRELATIVELT@minute@ahead@10^end_date>=javascript:gs.beginningOfLast30Minutes()/change_request"
    - name: fetch change tickets for post validation
      action: Fetch_change_tickets query1="{{ query }}"
      register: result
    - debug: var=result.response

    - set_fact:
        numbers: "{{ result.response }}"
    - debug: var=numbers
    - block:
        - debug:
            msg: "Call post validation role"
        - include_tasks: bots/Device silencing/Post_Validation.yml
          loop: "{{ numbers }}"
          loop_control: 
            loop_var: ch_number
          ignore_errors: yes
       
       
      when: "'string indices must be integers' not in numbers"
