- name: test
  hosts: localhost
  tasks:
    - set_fact:
        #query: 'short_descriptionLIKEInformational Change^end_date<javascript:gs.beginningOfCurrentMinute()^state=-1^end_date>javascript:gs.beginningOfLast15Minutes()/change_request'
        query: 'short_descriptionSTARTSWITHInformational Change^end_date<=javascript:gs.endOfCurrentMinute()^state=-1^end_date>=javascript:gs.beginningOfLast15Minutes()/change_request'
                
                                             
    - name: fetch change tickets to move from Implement to review
      action: Fetch_change_tickets query1="{{ query }}"
      register: result
    - debug: var=result.response
    - set_fact:
        numbers: "{{ result.response }}"
    - debug: var=numbers
    - block:
        - debug:
            msg: "Move tickets from implement to review"
        - include_tasks: bots/Prisma migration/Implement_to_review.yml
          loop: "{{ numbers }}"
          loop_control: 
            loop_var: ch_number
          ignore_errors: yes
      when: "'string indices must be integers' not in numbers"

