 - name: Execute command
   action: CommandExecution hostname='{{ incident_hostname }}' command='show sysenv temp' incidentno='{{ incident_no }}' notesupdate='no' 
   register: temp_status_register
   ignore_errors: true

 - debug: var=temp_status_register
 - set_fact:
     temp_text: "{{ temp_status_register.Output }}"

 - action: update_notes incident='{{ incident_no }}' work_notes='{{ temp_text }}'
   register: update_notes
 - debug: var=update_notes


#  - name: Set temp_text from command output (source of truth)
#    ansible.builtin.set_fact:
#         temp_text: "dl: @ge vernova dt cto network firewall supportreport problems @gevernovadtctonetworkfirewallsupport@ge.com name:domain: gdn.ge.comlocation code:as-chn-ln-syg-110161-2xingu  ==================================================================================================:tacp-0 term len 0clinfr0329  invalid command:'term len 0'.:tacp-0 hardware informationname                          value       unit            type          status    maximum     minimum     system temp 1                  39.00        celsius         temperature    0         75.0         0           system temp 2                  40.50        celsius         temperature    0         75.0         0           cpu temp                       29.00        celsius         temperature    0         77.0         0           :tacp-0 "
 - debug: 
    var: temp_text
    verbosity: 0
 - name: test
   ansible.builtin.set_fact:
    system_temp_1_str: "{{ temp_text | regex_search('System\\s+Temp\\s+1\\s+([0-9]+\\.[0-9]+)', '\\1', ignorecase=True) | first }}"   
   ignore_errors: yes
 - name: test
   ansible.builtin.set_fact:
    system_temp_2_str: "{{ temp_text | regex_search('System\\s+Temp\\s+2\\s+([0-9]+\\.[0-9]+)', '\\1', ignorecase=True) | first }}" 
   ignore_errors: yes
 - name: test
   ansible.builtin.set_fact:
    CPU_temp_str:  "{{ temp_text | regex_search('CPU\\s+Temp\\s+([0-9]+\\.[0-9]+)', '\\1', ignorecase=True) | first }}"
   ignore_errors: yes
 - debug: var=system_temp_1_str
 - debug: var=system_temp_2_str
 - debug: var=CPU_temp_str

 - set_fact:
    Temperature_notes: |- 
      [code]<h3> Temperature: </h3>[/code]
      system_temp_1: "{{ system_temp_1_str }}"
      system_temp_2: "{{ system_temp_2_str }}"
      CPU_temp: "{{ CPU_temp_str }}"
   ignore_errors: yes

 - action: update_notes incident='{{ incident_no }}' work_notes='{{ Temperature_notes }}'
   register: update_notes
 - debug: var=update_notes

 - name: Check whether all temperatures were fetched
   ansible.builtin.set_fact:
    temp_fetch_success: >-
      {{
        (system_temp_1_str | default('') | trim != '') and
        (system_temp_2_str | default('') | trim != '') and
        (CPU_temp_str | default('') | trim != '')
      }}
   ignore_errors: yes

 - block: 
    - debug:
       msg: "Unable to fetch temperature"
    - action: update_notes incident='{{ incident_no }}' work_notes='[code]<h3> Unable to fetch temperature values.</h3>[/code]'
      register: update_notes
    - debug: var=update_notes
    - meta: end_play
   when: not temp_fetch_success


 - block: 
    - debug:
       msg: "Raise Ticket"
    - action: update_notes incident='{{ incident_no }}' work_notes='[code]<h3> Temperature values are above 70 C.</h3>[/code]'
      register: update_notes
    - debug: var=update_notes
   when:
    - check_number == 4
    - temp_fetch_success
    - >
      (system_temp_1_str | float) > 70 or (system_temp_2_str | float) > 70 or (CPU_temp_str | float) > 70

 - block: 
    - debug:
       msg: "Close Ticket"
    - action: update_notes incident='{{ incident_no }}' work_notes='[code]<h3> Temperature values are below 70 C. Closing this Incident.</h3>[/code]'
      register: update_notes
    - debug: var=update_notes
   when:
    - check_number == 4
    - temp_fetch_success
    - (system_temp_1_str | float) <= 70
    - (system_temp_2_str | float) <= 70
    - (CPU_temp_str | float) <= 70
